#!/bin/bash

#print distor info
printf "%s (%s %s %s)\n" "$(lsb_release -s -d)" "$(uname -o)" "$(uname -r)" "$(uname -m)"

#big hostname
figlet -f small $(hostname) | /usr/games/lolcat -f

#uptime
uptime | /usr/games/lolcat -f

#need reboot?
cat /var/run/reboot-required | /usr/games/lolcat -f
