#!/bin/bash

#print distor info
printf "%s (%s %s %s)\n" "$(lsb_release -s -d)" "$(uname -o)" "$(uname -r)" "$(uname -m)"

#big hostname
figlet -f small $(hostname) | /usr/games/lolcat -f

#uptime
uptime | /usr/games/lolcat -f

#need reboot?
if [ -f /var/run/reboot-required ]; then
    /usr/games/cowsay "bruh you gotta reboot, it's required..." | /usr/games/lolcat -f
fi
